name: Go
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        go-version:
          - "1.8"
          - "1.11"
          - "1.x"
        exclude:
          - os: macOS-latest
            go-version: "1.8" 
    runs-on: ${{matrix.os}}
    steps:

    - name: Setup Go ${{matrix.go-version}}
      uses: actions/setup-go@v1
      with:
        go-version: ${{matrix.go-version}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: ./runtests.sh
